[package]
name = "vpe"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"

[profile.dev]
opt-level = 0
[profile.dev.package."*"]
opt-level = 3
[profile.dev.package.vpb]
opt-level = 0

[dependencies]
vpb = { path="vp-base" }